### ISSUE TITLE
请问作者_geometric.nn用的什么版本

### ISSUE THREAD

**Issue by shuqincao** [slingling/MS-HGAT#2]
init.xavier_normal_(self.gnn1.weight)报错 torch.nn.modules.module.ModuleAttributeError: 'GCNConv' object has no attribute 'weight'

**Comment by slingling** [comment]
torch_geometric 1.6.3

**Comment by WhiteRookie** [comment]
> init.xavier_normal_(self.gnn1.weight)报错 torch.nn.modules.module.ModuleAttributeError: 'GCNConv' object has no attribute 'weight'

我也是这个错误  你解决了吗
