### ISSUE TITLE
有关论文的三个问题

### ISSUE THREAD

**Issue by 869277160** [slingling/MS-HGAT#7]
1、请问作者，您在公开的代码中使用了全部的级联信息构建动态超图，一般来说应该仅使用训练集构建超图，是否会存在有部分关联关系泄露使得模型效果提升呢？

2、此外，您在公开的代码中划分数据集的时候使用的是最长为500的级联构建数据集，之后在训练和预测的时候，则是使用以200为最大长度的截断后的级联数据进行预测，请问两者不一致是否会在动态超图中引入噪声？导致模型性能下降？

3、在RQ2中，您改变了Training Set Proportion 进行实验，为了说明模型在不同训练数据下都可以取得良好的效果，那么对应测试集还是原来相同的测试集么？

**Comment by head-bigandhard** [comment]
> 您好，请问第一个问题您解决了吗？是否确实存在信息泄露呢？

**Comment by 869277160** [comment]
解决了，我个人认为不算，只要作者不使用测试集中的数据进行训练就不算泄露。

**Comment by 869277160** [comment]
第二个问题，个人认为不算问题，因为在缩小模型的预测长度之后，效果依旧达到了较好的效果，说明模型可以屏蔽相关噪声信息。
第三个问题不算问题，可以进行复现。因此本人决定关闭此issue

**Comment by head-bigandhard** [comment]
请问您在所有数据集都进行了实验吗？效果和论文中给的数值差异大吗？

**Comment by 869277160** [comment]
您好，我进行了实验，效果差异不大，我认为是显卡以及实现方法的问题。
